### ISSUE TITLE
Database Issues glpi_plugin_formcreator_forms_answers -> glpi_plugin_formcreator_formanswers

### ISSUE THREAD

**Issue by fgendorf** [pluginsGLPI/formcreator#1370]
**Describe the bug**
on the version 2.7 the table glpi_plugin_formcreator_forms_answers was change to glpi_plugin_formcreator_formanswers, but the columns have differs, like in issue.class.php
the function cronSyncIssues use users_id_validator, but this columns not exist anymore, now is validator_id I suppose.

**Comment by Stoatwblr** [comment]
I see the same thing.

SQL error log:

```
 Error: Unknown column 'fanswer.users_id_validator' in 'field list'
  Backtrace :
  plugins/formcreator/inc/issue.class.php:125
  inc/crontask.class.php:829                         PluginFormcreatorIssue::cronSyncIssues()
  front/cron.php:88                                  CronTask::launch()
  {"user":"@msslyz.mssl.ucl.ac.uk"}
                  `fanswer`.`request_date`       AS `date_mod`,
                  `fanswer`.`entities_id`        AS `entities_id`,
                  `fanswer`.`is_recursive`       AS `is_recursive`,
                  `fanswer`.`requester_id`       AS `requester_id`,
                  `fanswer`.`users_id_validator` AS `validator_id`,
                  `fanswer`.`comment`            AS `comment`
               FROM `glpi_plugin_formcreator_formanswers` AS `fanswer`
               LEFT JOIN `glpi_plugin_formcreator_forms` AS `f`
                  ON`f`.`id` = `fanswer`.`plugin_formcreator_forms_id`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`items_id` = `fanswer`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               WHERE `fanswer`.`is_deleted` = '0'
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`tickets_id`) != 1

               UNION

               SELECT DISTINCT
                  NULL                          AS `id`,
                  CONCAT('t_',`tic`.`id`)       AS `display_id`,
                  `tic`.`id`                    AS `original_id`,
                  'Ticket'                      AS `sub_itemtype`,
                  `tic`.`name`                  AS `name`,
                  `tic`.`status`                AS `status`,
                  `tic`.`date`                  AS `date_creation`,
                  `tic`.`date_mod`              AS `date_mod`,
                  `tic`.`entities_id`           AS `entities_id`,
                  0                             AS `is_recursive`,
                  `tic`.`users_id_recipient`    AS `requester_id`,
                  0                             AS `validator_id`,
                  `tic`.`content`               AS `comment`
               FROM `glpi_tickets` AS `tic`
               LEFT JOIN `glpi_items_tickets` AS `itic`
                  ON `itic`.`tickets_id` = `tic`.`id`
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'
               WHERE `tic`.`is_deleted` = 0
               GROUP BY `original_id`
               HAVING COUNT(`itic`.`items_id`) <= 1) AS `issues`
```

**Comment by btry** [comment]
Hi

I think you both had an upgrade issue when you upgraded from Formcreator < 2.6.0 to 2.6.0.

users_id_validator and groups_id_validator are 2 new columns added in 2.6.0 to address a semantic issue in a column which contained either a users_id or a groups_id depending on some other data. If you don't have users_id_validator and groups_id_validator then you probably encounteer bugs for long (or you did not used any form with validation).

Please compare the table against its CREATE TABLE statement in instal/mysql/plugin_formcreator_empty.sql

https://github.com/pluginsGLPI/formcreator/blob/v2.8.0/install/mysql/plugin_formcreator_empty.sql

**Comment by 4n63lu5** [comment]
I have the same problem

may be the begin of an answer

in upgrade_to_2.7.php we found

```
 $table = 'glpi_plugin_formcreator_formanswers';
 $migration->renameTable('glpi_plugin_formcreator_forms_answers', $table);
```

but at least in formcreator/inc/form.class.php line 864 we found 
`INNER JOIN glpi_plugin_formcreator_formanswers fa ON f.`id` = 

and in formcreator/inc/issue.class.php line 81,90,95,118  we found 
                  AND `itic`.`itemtype` = 'PluginFormcreatorFormAnswer'

renaming glpi_plugin_formcreator_formanswers to glpi_plugin_formcreator_forms_answers in the code ???

**Comment by btry** [comment]
Hi @4n63lu5 

No, In 2.7 I renamed the itemtype PluginFormcreatprForm_Answer into PluginFormceatorFormAnswer. This is wanted.

If the columns differ, this is very likely due to a problem caused un a previous upgrade. Renaming a table will keep all columns and data unchanged. Only the name of the table is updated.

Other users did not give feedback, then I'm stuck.

Please compare the table against its CREATE TABLE statement in install/mysql/plugin_formcreator_empty.sql

https://github.com/pluginsGLPI/formcreator/blob/v2.8.0/install/mysql/plugin_formcreator_empty.sql

**Comment by 4n63lu5** [comment]
i found this table in my db


                      CREATE TABLE `glpi_plugin_formcreator_forms_answers` (
                      `id` int(11) NOT NULL,
                      `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
                      `entities_id` int(11) NOT NULL DEFAULT 0,
                      `is_recursive` tinyint(1) NOT NULL DEFAULT 0,
                      `plugin_formcreator_forms_id` int(11) NOT NULL,
                      `requester_id` int(11) DEFAULT NULL,
                      `users_id_validator` int(11) NOT NULL DEFAULT 0,
                      `groups_id_validator` int(11) NOT NULL DEFAULT 0,
                      `request_date` datetime NOT NULL,
                      `status` enum('waiting','refused','accepted') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'waiting',
                      `comment` text COLLATE utf8_unicode_ci DEFAULT NULL,
                      `is_deleted` tinyint(1) NOT NULL DEFAULT 0
                      ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

`requester_id` int(11) DEFAULT NULL,
`users_id_validator` int(11) DEFAULT NULL,
`groups_id_validator` int(11) DEFAULT NULL,
`request_date` datetime NOT NULL,
`status` enum('waiting','refused','accepted') NOT NULL DEFAULT 'waiting',
`comment` text,
                      CREATE TABLE `glpi_plugin_formcreator_formanswers` (
                      `id` int(11) NOT NULL,
                      `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
                      `entities_id` int(11) NOT NULL DEFAULT 0,
                      `is_recursive` tinyint(1) NOT NULL DEFAULT 0,
                      `plugin_formcreator_forms_id` int(11) NOT NULL,
                      `requester_id` int(11) DEFAULT NULL,
                      `validator_id` int(11) DEFAULT NULL,
                      `request_date` datetime NOT NULL,
                      `status` enum('waiting','refused','accepted') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'waiting',
                      `comment` text COLLATE utf8_unicode_ci DEFAULT NULL
                      ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



and 

`users_id_validator` int(11) DEFAULT NULL,
`groups_id_validator` int(11) DEFAULT NULL,

doesn't exist in glpi_plugin_formcreator_formanswers in my db in comparison to plugin_formcreator_empty.sql

more
it seems that glpi_plugin_formcreator_forms_answers doesn't exist in plugin_formcreator_empty.sql

**Comment by btry** [comment]
It  appears that your table glpi_plugin_formcreator_forms_answers was not renamed.

After this rename, some column names should be updated to match the renamed itemtype.

```php
      $table = 'glpi_plugin_formcreator_answers';
      $migration->changeField(
         $table,
         'plugin_formcreator_forms_answers_id',
         'plugin_formcreator_formanswers_id',
         'integer'
      );
```

Can you check in this table the name of the foreign key to formanswer ? (I want to see if the upgrade code was at least partially exeecuted).

**Comment by jvergacas** [comment]
I do not know if it's the same problem, but mine is getting the wrong fields when searching for open tickets.
![image](https://user-images.githubusercontent.com/43650152/56383254-d16a6680-61ef-11e9-91a4-d1f12e282853.png)

**Comment by btry** [comment]
Hi @jvergacas 

If you"re not using the version 2.8.1, please use your testing environment to upgrade the plugin, then truncate the table glpi_plugin_formcreator_issues, and run the automatic action **SyncIssues**.  This should fix it.

**Comment by jvergacas** [comment]
Hi @btry 

I noticed the problem after upgrading to 2.8.1

Even clearing the glpi_plugin_formcreator_issues table, the problem returns after running the automatic action SyncIssues.

**Comment by btry** [comment]
Hi @jvergacas 

This is an issue I found a few weeks ago. I checked the code and I confirm it is fixed in 2.8.1.

Please compare the order of the columns of the issues table of the plugin with the order of the columns of the result of the big SQL query in inc/issues.class.php of your local copy of the plugin

https://github.com/pluginsGLPI/formcreator/blob/develop/inc/issue.class.php#L76

Name must be in 2nd position for both. I missed to update the order of columns in inc/issues.class.php, causing the bug. The link above points to a fixed version of the file.

**Comment by jvergacas** [comment]
@btry 

The table structure was wrong, I corrected the DB, cleaned the table and performed automatic action.

Thanks a lot for the help.

**Comment by btry** [comment]
Great ! 

Now, the initial problem : @fgendorf @Stoatwblr Do the problem persist ?

**Comment by fgendorf** [comment]
Hi, the problem disappear in version 2.8.1, but I need fix tables manually,
according with
https://github.com/pluginsGLPI/formcreator/blob/develop/install/mysql/plugin_formcreator_empty.sql
, in some point the upgrade process doesn't work well
_________________________
Frederico Gendorf

**Comment by btry** [comment]
HI

@fgendorf The column ```name``` of the table issue shall move after the column ```id``` when you upgraded from a version < 2.7.0 to 2.7.0 or later.

I think you may find the date of the upgrade in glpi/files/_log/ a migration log migration_to_x.y.z.log should exist wuth x, y and z a version >= 2.7.0.

Please check this log, the data in files/_log/php-errors.log and files/_log/sql-errors.log near the date of the first file. 

The related code is here: https://github.com/pluginsGLPI/formcreator/blob/develop/install/upgrade_to_2.7.php#L288 . You may also want to check if the column ```name``` of the other tables moved to after ```id```.

**Comment by Stoatwblr** [comment]
Sorry, I can't update - Blew away the plugin & tables and reinstalled from scratch.

**Comment by btry** [comment]
Hi

Then the problem is solved (however the cause is unknown).
