### ISSUE TITLE
Object entity not recursive

### ISSUE THREAD

**Issue by chnateag** [pluginsGLPI/formcreator#2242]
**Describe the bug**
Same bug as #2235 #2232  but for entities

**To Reproduce**
GLPI 9.5.5 / Formcreator 2.11.3
Create a form with glpi object / entity selection in recursive mode
Clic on drop down

**Expected behavior**
A list of complete childs entities

**Screenshots**
![image](https://user-images.githubusercontent.com/6058178/117814338-77202080-b264-11eb-8e5d-62853309cce7.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser FF / Chrome

**Additional context**
The fix #2232 didn't work

thank you guys

**Comment by btry** [comment]
Hi

I assume that you have sub entities under "Entité racine > Clients". 

In which entity is located the user, and do this user have recursion enabld in his authorizations ?

![image](https://user-images.githubusercontent.com/14139801/117818106-93be5780-b268-11eb-917d-72fa67741e87.png)

**Comment by chnateag** [comment]
Yes i confirm our entity Clients has sub entities

this was a test with glpi user : 
![image](https://user-images.githubusercontent.com/6058178/117819439-d46aa080-b269-11eb-8848-a92ea52d7d0c.png)

**Comment by btry** [comment]
You need to enable recursion on the form itself. I understood that you did it, but in my instance the dropdown behaves as expected (in other words, I don't reproduce your issue). 

Please double check this setting. Do not forget that if you need to change it you shall refresh the whole page with F5.  If not, the preview won't take the change into account. 

![image](https://user-images.githubusercontent.com/14139801/117826043-21ea0c00-b270-11eb-8c7b-a72fb64feb5c.png)

**Comment by btry** [comment]
It appears you apply fixed by overwriting files. This is not the good way, and you will one day or an other break the plugin.

Reinstall the release of Formcreator, get a coffee and learn how to use the patch tool. Once done, get the .diff file of the pull request and apply it.

**Comment by chnateag** [comment]
Okay so i started from fresh with git : 
```
git clone https://github.com/pluginsGLPI/formcreator.git
cd formcreator/
git checkout support/2.11.0
wget https://patch-diff.githubusercontent.com/raw/pluginsGLPI/formcreator/pull/2233.patch
git apply 2233.patch
git checkout :
M       inc/field/dropdownfield.class.php
Votre branche est à jour avec 'origin/support/2.11.0'.
```

So now in my question when i set up the glpi object i have access to all my entities in drop down, but not when in form i still can't.

Hope i did good this time. I cleared cache, tried in private navigation, put the form recursive off and on again, log out...

**Comment by btry** [comment]
Hi

In which entity is the form, and does it have recursion ?

![image](https://user-images.githubusercontent.com/14139801/117826043-21ea0c00-b270-11eb-8c7b-a72fb64feb5c.png)

**Comment by chnateag** [comment]
I think we're all good
![image](https://user-images.githubusercontent.com/6058178/118487244-cf4e9b00-b71a-11eb-8232-0cae25aff1f9.png)
![image](https://user-images.githubusercontent.com/6058178/118490349-24d87700-b71e-11eb-9031-0abd0681bf98.png)

**Comment by btry** [comment]
Hi

Yes, it looks good. So far I don't reproduce, then I guess you should check the entities available for the user. If I remember well you did not answered to my question about the entities the user can use with his current profile.

**Comment by chnateag** [comment]
Yes sorry if i wasn't clear, i didn't really check because i'm testing with GLPI default user which has : 

root entity with super admin privileges in recursive mode, so i can use every entities

**Comment by btry** [comment]
So far I could not reproduce, and I used the default account **glpi** (then, I'm in rot entity, and I have recursion enabled).

If you have some skills with PHP and xdebug, you should maybe investigate how PHP GLPI behaves when it computes the available items of the dropdown. You need to check how are applied the entity restrictions, compared to the restrictions defined in the variable $dparams of the above code fragment.

**Comment by fahcdo** [comment]
Hello
I have the same problem.
Since the update of the plugin, in my forms I no longer have access to the sub-entity

**Comment by chnateag** [comment]
@btry i have some skills with php but not xdebug, i'll take a look at it
@fahcdo thank you i feel less alone

**Comment by fahcdo** [comment]
![2021-05-17 16_12_26-Window](https://user-images.githubusercontent.com/6009687/118503519-fca34500-b72a-11eb-8906-c5e55e63d292.png)
![2021-05-17 16_10_48-Window](https://user-images.githubusercontent.com/6009687/118503516-fc0aae80-b72a-11eb-8a2b-9bf421675094.png)
![2021-05-17 16_11_13-Window](https://user-images.githubusercontent.com/6009687/118503518-fca34500-b72a-11eb-840f-ac7362b05c0b.png)

**Comment by Blank-Vcf** [comment]
Same here updated glpi to 9.5.5 and formcreator to 2.11.3 and missing access to sub entity

**Comment by btry** [comment]
Hi

Thanks @Blank-Vcf : this confirms that @chnateag has something still unknown which causes his problem.

@chnateag the latest feedback indicates that you may have a configuration (or user context) problem.

**Comment by btry** [comment]
@fahcdo : try the above patch and see if it works for you as well.

**Comment by fahcdo** [comment]
Hello
I just did it, no change for me

**Comment by btry** [comment]
Can one of those still impacted apply the following patch (for debug purpose) ? It will write un glpi/files/_log/php-errors.log some data in a JSON string, to share here.

```diff
diff --git a/inc/field/dropdownfield.class.php b/inc/field/dropdownfield.class.php
index 5f83cb1e..42cf971e 100644
--- a/inc/field/dropdownfield.class.php
+++ b/inc/field/dropdownfield.class.php
@@ -381,6 +381,7 @@ class DropdownField extends PluginFormcreatorAbstractField
             $params['_idor_token'] = Session::getNewIDORToken($itemtype);
          }
          $html .= $itemtype::dropdown($dparams);
+         \Toolbox::logError(json_encode($dparams));
       }
       $html .= PHP_EOL;
       $html .= Html::scriptBlock("$(function() {
```

**Comment by chnateag** [comment]
Hello, is that what you're looking for ?

`[2021-05-18 15:30:59] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /home/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 3 found!  {"user":"34@glpi"}`

**Comment by btry** [comment]
@chnateag : no. This kind of error shows there is probably a design error in GLPI or a plugin. You should read teh backtrace if this error and report the bug to the appropriate project.


Here is a sample of the expected output

```
[2021-05-18 15:06:29] glpiphplog.ERROR: GlpiPlugin\Formcreator\Field\DropdownField::getRenderedHtml() in /home/tbugier/public_html/glpi-95/a/plugins/formcreator/inc/field/dropdownfield.class.php line 384
{"name":"formcreator_field_188","value":"0","display":false,"comments":false,"entity":0,"entity_sons":true,"displaywith":["id"],"rand":248703710,"condition":[],"display_emptychoice":true}  {"user":"2@deepthought"} 
````

**Comment by chnateag** [comment]
okay, so the patch is applied i checked : 

`root@glpi:/var/www/glpi/plugins/formcreator# grep -ri -A 10 -B 10 _idor_token inc/field/dropdownfield.class.php
      }

      $html        = '';
      $id           = $this->question->getID();
      $rand         = mt_rand();
      $fieldName    = 'formcreator_field_' . $id;
      if (!empty($this->question->fields['values'])) {
         $dparams = $this->buildParams($rand);
         $dparams['display'] = false;
         if (version_compare(GLPI_VERSION, '9.5.3') >= 0) {
            $params['_idor_token'] = Session::getNewIDORToken($itemtype);
         }
         $html .= $itemtype::dropdown($dparams);
         \Toolbox::logError(json_encode($dparams));
      }
      $html .= PHP_EOL;
      $html .= Html::scriptBlock("$(function() {
         pluginFormcreatorInitializeDropdown('$fieldName', '$rand');
      });");

      return $html;
`
I have no output when i open a form, do a control + f5, and then try to pick an entity in the dropdown

**Comment by btry** [comment]
I think that you don't enter in the if { ... } block. 

Try to edit the question, reviex its settings and save. If everything looks god, click on the save buton anyway. You may have a inconsistency in the DB for the question. 

Next, check if the problem goes away.

**Comment by btry** [comment]
Actually, you must enter in the if () block. If not, the dropdown would not display.

I see often users having 2 copies of Formcreator in their GLPI instance because they switched from regular plugin isntallation to marketplace installation. Please check if you find Formcreator in the plugins director and in the marketplace directory.

If yes,  then you must delete one of them.

**Comment by fahcdo** [comment]
It is OK for me
I had two installations.
the following code works
```
$dparams = [
         'name'     => $fieldName,
         'value'    => $this->value,
         'display'  => false,
         'comments' => false,
         'entity'   => $form->fields['entities_id'],
         'entity_sons' => (bool) $form->isRecursive(),
         'displaywith' => ['id'],
      ];

```

And for log

```
[2021-05-18 16:19:06] glpiphplog.ERROR: GlpiPlugin\Formcreator\Field\DropdownField::getRenderedHtml() in /var/www/html/glpi/marketplace/formcreator/inc/field/dropdownfield.class.php line 384
{"name":"formcreator_field_8","value":"0","display":false,"comments":false,"entity":0,"entity_sons":true,"displaywith":["id"],"rand":1837271876,"right":"all","condition":[],"display_emptychoice":true}  {"user":"867@srv-glpi-arc"} 
[2021-05-18 16:19:06] glpiphplog.ERROR: GlpiPlugin\Formcreator\Field\DropdownField::getRenderedHtml() in /var/www/html/glpi/marketplace/formcreator/inc/field/dropdownfield.class.php line 384
{"name":"formcreator_field_11","value":"-1","display":false,"comments":false,"entity":0,"entity_sons":true,"displaywith":["id"],"rand":173460510,"condition":[],"display_emptychoice":true}  {"user":"867@srv-glpi-arc","mem_usage":"0.001\", 4.08Mio)"} 
[2021-05-18 16:19:06] glpiphplog.ERROR: GlpiPlugin\Formcreator\Field\DropdownField::getRenderedHtml() in /var/www/html/glpi/marketplace/formcreator/inc/field/dropdownfield.class.php line 384
{"name":"formcreator_field_10","value":"0","display":false,"comments":false,"entity":0,"entity_sons":true,"displaywith":["id"],"rand":961581058,"condition":{"OR":{"is_incident":1,"is_request":1}},"display_emptychoice":true}  {"user":"867@srv-glpi-arc","mem_usage":"0.001\", 4.10Mio)"} 

```

**Comment by btry** [comment]
@fahcdo : 

> It is OK for me

So the bug does not occurs anymore for you ?

**Comment by fahcdo** [comment]
yes it is solved

**Comment by fahcdo** [comment]
thank you so much

**Comment by btry** [comment]
Nice ! Now I'm waiting  for feedback from @chnateag

**Comment by chnateag** [comment]
Dear god. i didn't eaven know there was a marketplace directory. A co-worker tried to install it, there is a directory indeed

**Comment by chnateag** [comment]
Well the good news is it does work a lot better now (giant facepalm)
the bad news is we've lost half of our most complex forms and someone is going to kill himself at the office.
Is there a way to make my sql backup / json export working with this update ?

Not the best place to get help i've got this when enabling the plugin with the old database : 

`
Done (1 second)

Done (1 second)

SQL Error "1146": Table 'glpi.glpi_plugin_formcreator_targets' doesn't exist in query "SELECT * FROM `glpi_plugin_formcreator_targets`"
Done (2 seconds)

glpi_plugin_formcreator_formanswers table already exists. A backup have been done to backup_glpi_plugin_formcreator_formanswers

You can delete backup tables if you have no need of them.

SQL Error "1146": Table 'glpi.glpi_plugin_formcreator_formanswers' doesn't exist in query "DELETE `glpi_plugin_formcreator_formanswers` FROM `glpi_plugin_formcreator_formanswers` WHERE `is_deleted` = '1'"
PHP User Warning (512): Table glpi_plugin_formcreator_formanswers does not exists in /home/www/glpi/inc/dbmysql.class.php at line 1028
Done (2 seconds)

PHP User Warning (512): Table glpi_plugin_formcreator_targetchanges_actors does not exists in /home/www/glpi/inc/dbmysql.class.php at line 1028
Done (2 seconds)

Done (2 seconds)

SQL Error "1146": Table 'glpi.glpi_plugin_formcreator_formanswers' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_formcreator_formanswers` WHERE Field = 'status'"
SQL Error "1146": Table 'glpi.glpi_plugin_formcreator_targetchanges_actors' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_formcreator_targetchanges_actors` WHERE Field = 'actor_role'"
SQL Error "1146": Table 'glpi.glpi_plugin_formcreator_targetchanges_actors' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_formcreator_targetchanges_actors` WHERE Field = 'actor_type'"
SQL Error "1146": Table 'glpi.glpi_plugin_formcreator_targettickets_actors' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_formcreator_targettickets_actors` WHERE Field = 'actor_role'"
SQL Error "1146": Table 'glpi.glpi_plugin_formcreator_targettickets_actors' doesn't exist in query "SHOW COLUMNS FROM `glpi_plugin_formcreator_targettickets_actors` WHERE Field = 'actor_type'"
Done (2 seconds)

Done (3 seconds)

SQL Error "1146": Table 'glpi.glpi_plugin_formcreator_formanswers' doesn't exist in query "SELECT COUNT(*) AS cpt FROM ((SELECT DISTINCT NULL as `id`, `glpi_plugin_formcreator_forms`.`name` AS `name`, CONCAT('f_', `glpi_plugin_formcreator_formanswers`.`id`) as `display_id`, `glpi_plugin_formcreator_formanswers`.`id` AS `original_id`, 'PluginFormcreatorFormAnswer' as `sub_itemtype`, `glpi_plugin_formcreator_formanswers`.`status` AS `status`, `glpi_plugin_formcreator_formanswers`.`request_date` AS `date_creation`, `glpi_plugin_formcreator_formanswers`.`request_date` AS `date_mod`, `glpi_plugin_formcreator_formanswers`.`entities_id` AS `entities_d`, `glpi_plugin_formcreator_formanswers`.`is_recursive` AS `is_recursive`, `glpi_plugin_formcreator_formanswers`.`requester_id` AS `requester_id`, `glpi_plugin_formcreator_formanswers`.`users_id_validator` AS `users_id_validator`, `glpi_plugin_formcreator_formanswers`.`groups_id_validator` AS `groups_id_validator`, `glpi_plugin_formcreator_formanswers`.`comment` AS `comment` FROM `glpi_plugin_formcreator_formanswers` LEFT JOIN `glpi_plugin_formcreator_forms` ON (`glpi_plugin_formcreator_forms`.`id` = `glpi_plugin_formcreator_formanswers`.`plugin_formcreator_forms_id`) LEFT JOIN `glpi_items_tickets` ON (`glpi_items_tickets`.`items_id` = `glpi_plugin_formcreator_formanswers`.`id` AND `glpi_items_tickets`.`itemtype` = 'PluginFormcreatorFormAnswer') GROUP BY `original_id` HAVING COUNT(`glpi_items_tickets`.`tickets_id`) != 1) UNION (SELECT DISTINCT NULL as `id`, `glpi_tickets`.`name` AS `name`, CONCAT('t_', `glpi_tickets`.`id`) as `display_id`, `glpi_tickets`.`id` AS `original_id`, 'Ticket' as `sub_itemtype`, IF(`glpi_ticketvalidations`.`status` IS NULL, `glpi_tickets`.`status`, IF(`glpi_tickets`.`global_validation` IN ('1', '3'), `glpi_tickets`.`status`, IF(`glpi_tickets`.`status` IN ('5', '6'), `glpi_tickets`.`status`, IF(`glpi_tickets`.`global_validation` = '2', '101', '102' ) ) ) ) AS `status`, `glpi_tickets`.`date` AS `date_creation`, `glpi_tickets`.`date_mod` AS `date_mod`, `glpi_tickets`.`entities_id` AS `entities_id`, 0 as is_recursive, `glpi_tickets_users`.`users_id` AS `requester_id`, IF(`glpi_ticketvalidations`.`users_id_validate` IS NULL, 0, `glpi_ticketvalidations`.`users_id_validate`) as users_id_validator, 0 as groups_id_validator, `glpi_tickets`.`content` AS `comment` FROM `glpi_tickets` LEFT JOIN `glpi_items_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id` AND `glpi_items_tickets`.`itemtype` = 'PluginFormcreatorFormAnswer') LEFT JOIN (SELECT * FROM (SELECT DISTINCT `users_id`, `tickets_id` FROM `glpi_tickets_users` WHERE `type` = '1' ORDER BY `id` ASC) AS `inner_glpi_tickets_users` GROUP BY `tickets_id`) AS `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`) LEFT JOIN `glpi_ticketvalidations` ON (`glpi_tickets`.`id` = `glpi_ticketvalidations`.`tickets_id`) WHERE `glpi_tickets`.`is_deleted` = '0' GROUP BY `original_id` HAVING COUNT(`glpi_items_tickets`.`items_id`) <= 1)) AS `union_9ba94fed87bfc87173ec2e7052f4de49`"
PHP Notice (8): Trying to access array offset on value of type bool in /home/www/glpi/marketplace/formcreator/inc/issue.class.php at line 231
Done (3 seconds)

Data migration - glpi_displaypreferences (3 seconds)

PHP User Warning (512): Table glpi_plugin_formcreator_formanswers does not exists in /home/www/glpi/inc/dbmysql.class.php at line 1028`

**Comment by btry** [comment]
> JSON export / import 

If you mean forms exported in JSON files, you can import them if you use the same version of Formcreator. If you need to import from older version you may build a fresh GLPI + Formcreator of that old version, import the forms, then upgrade the plugin and finally export again.

If you need to recover other data (answers) then you need to restore the database from your backup.  There is no feature to import data from answers in the plugin.

Maybe the simplese would be to restore the plugin and the DB to a state before you removed the duplicate installation of the plugin then test a upgrade scenario on a testing environment.

I hope that helps you, and don't let your colleague killing himself. Encourage him to backup :)

**Comment by chnateag** [comment]
okay, we'll try that, thank you very much !
