### ISSUE TITLE
Cant' find KB document in formcreator if plug in set on " merge with form"

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2287]
**Describe the bug**
Cant' find KB document in formcreator if plug in set on " merge with form"

**To Reproduce**
1.
![fusion](https://user-images.githubusercontent.com/78594318/123918985-bb868d80-d984-11eb-8f25-fa7f2bf15f43.jpg)
Set plug in on "merge with form"

2. Log in as a user
3. search the KB document.. 
4. can't find it..
5. Set plug in formcreator "distinct KB", search the doc as a user, then it's ok.
![kb2](https://user-images.githubusercontent.com/78594318/123919342-246e0580-d985-11eb-8420-731861dd04ca.jpg)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Win 10
Firefox
glpi 9.5.5 formcreator 2.11.4

**Additional context**

**Comment by btry** [comment]
HI

Only FAQ items are available. Please check that your KB document is configured as FAQ, and check also that the user is granded to read the KB item.

![image](https://user-images.githubusercontent.com/14139801/123920954-ce01c680-d986-11eb-8d07-88ddb85e9344.png)

**Comment by mirda123** [comment]
Hi, thank you for your quick answer

FAQ is set for the document.
If i Set plug in formcreator  on : "distinct KB", search the same doc as a user, then i find it 
![kb2](https://user-images.githubusercontent.com/78594318/123921854-be36b200-d987-11eb-9c35-0816a7f1a897.jpg)

If i Set plug in formcreator  on : "merge with forms", fir the same document, where am i supposed to find it next ?
here ?
![kb3](https://user-images.githubusercontent.com/78594318/123922375-42893500-d988-11eb-8c51-3c6000591131.jpg)
i can't find it

**Comment by btry** [comment]
When you select "merge with forms" the KB FAQ shall appear with forms. Then you might have an issue here.

Can you check if here are errors in php-errors.log or sql-errors.log ?

**Comment by mirda123** [comment]
nothing in php-errors.log / sql-errors.log
could it be related to this : 

![kb4](https://user-images.githubusercontent.com/78594318/123936778-ceee2480-d995-11eb-96d6-fe5f78503933.jpg)

![kb5](https://user-images.githubusercontent.com/78594318/123936651-ad8d3880-d995-11eb-9a8a-d7a8a464bcf4.jpg)

![kb6](https://user-images.githubusercontent.com/78594318/123936511-87679880-d995-11eb-8d05-256ff9e53621.jpg)

**Comment by mirda123** [comment]
that's it.. all my forms have no categories either... when  it's this way.. it does'nt work in "merge with forms" ...

**Comment by btry** [comment]
Yes, I forgot to mention that KB items must have a category, and the KB category mist be linked to a forms category.

**Comment by mirda123** [comment]
that's is yes ! now it works perfectly !  : ) 
Thank you very much !!

**Comment by mirda123** [comment]
![kb7](https://user-images.githubusercontent.com/78594318/123940610-a2d4a280-d999-11eb-9b80-10276658df5d.jpg)

results perfect : )

**Comment by btry** [comment]
You're welcome. As the problem is solved, I close.

**Comment by mirda123** [comment]
I still have a question : 

why does my document is not visible when i click on " voir tous" in "distinct KB mode" ? 
if i click on "voir tous" in "merge with forms mode" , i see it.
in "distinct KB mode", the user won't "think" to click on the category... he will think there are no docs here. 

![kb8](https://user-images.githubusercontent.com/78594318/123970846-ca3b6780-d9b9-11eb-8e5f-3d09db359d49.jpg)
![kb9](https://user-images.githubusercontent.com/78594318/123970861-cdceee80-d9b9-11eb-957d-56c7c6b6ae5d.jpg)

**Comment by btry** [comment]
Hi

> why is my document not visible when i click on " voir tous" in "distinct KB mode" ?
if i click on "voir tous" in "merge with forms mode" , i see it.
in "distinct KB mode", the user won't "think" to click on the category... he will think there are no docs here.

I need to investigate.
