### ISSUE TITLE
Validator still requires approval for their forms

### ISSUE THREAD

**Issue by xraive** [pluginsGLPI/formcreator#2846]
I have the plugin working but anytime a validator submits a form they are still required to approve it. 

1. Create a from that requires a validation from a validator
2. user the validator to complete a from
3. The validator receives a notification to approve their own form

A validator should be able to submit forms (at least the ones they are the validators for) with out requiring approval.

*I'm using formcreator version. 2.13 0-rc.1 and using GLPI Version 10.0.1. This is a brand new install with only the formcreator plugin installed.

**Comment by btry** [comment]
Hi

Is this issue also fixed by #2847 ?

**Comment by xraive** [comment]
I just did a test and forms submitted by the validator still show up with the status "Waiting".  I still need to go in and validate the request.

**Comment by btry** [comment]
OK. Try the above fix and feedback

**Comment by xraive** [comment]
This patch fixes the issue for Groups as well.

**Comment by btry** [comment]
Improvement merged in 2.13.0
