### ISSUE TITLE
Uncaught TypeError: can't access property "message", xhr.responseJSON is undefined

### ISSUE THREAD

**Issue by gjimenezt** [pluginsGLPI/formcreator#3040]
**Describe the bug**
Error when sending a form, if it has active validation.
When pressing the send button, it does not generate any action, if we update the tab with f5. the form is submitted.

**Expected behavior**
The form must be saved, send a validation request to the validator.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/115827009/195915267-1f84bbc1-65cf-4fa5-acc2-14110ec35fa1.png)

![imagen](https://user-images.githubusercontent.com/115827009/195915341-8f91f477-e2ee-4166-9cce-efb47b24b4d5.png)

**GLPI / Plugins (please complete the following information):**
Form Creator

- GLPI version
10.0.3

- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
- 

Form Creator
GPL v2+
TECLIB'
2.13.1

**Desktop (please complete the following information):**
 -Windows 11 
 - Firefox Developer
 - 106.0b9 (64 bits)
 -

**Comment by btry** [comment]
Hi

Some problems are already addressed, but not released yet (planned next week).

Apply this patch: https://github.com/pluginsGLPI/formcreator/commit/abed861018c4a04b3385c43223a2554eaf4dcaf7
it will disable the submit button after a click, and show a spinner to confirm the server is working.

If you use PHP 8.1 some other issues may impact the page reload after the clic on the submit button. Apply the following patches
https://github.com/pluginsGLPI/formcreator/commit/8ff7ff91a2811937ec6ad7b4d37cd909b99373dd
https://github.com/pluginsGLPI/formcreator/commit/297fb27133851d5c9cd470c422a360b1f9ecfe90

Once the fixes applied, test a form. If there is no redirection, please search in php-errors.log and sql-errors.log if there are erruors. Check also in the developer tools of the browser, in the JS console.

**Comment by gjimenezt** [comment]
Good morning **@Btry,** thanks for the help, I have applied the patches that you have indicated and I am able to send the forms correctly. Obs. The only thing that still does not work is if at the moment of pressing the SEND button, a question that is Required (*) has not been completed. the form disables the submit button, issues the alert that the question is necessary, but does not load. After that everything works.

**Comment by btry** [comment]
This patch should re-enable the button if the form fails to validate 3517ce028. Try it and feedback please, The next release is planned for the end of week.

**Comment by gjimenezt** [comment]
> This patch should re-enable the button if the form fails to validate [3517ce0](https://github.com/pluginsGLPI/formcreator/commit/3517ce028240848830f52421424a5f6d830bfcdc). Try it and feedback please, The next release is planned for the end of week.

Excellent @Btry, now it is working correctly. Thank you very much for your time and for the help provided.
